### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [Cj-Malone/Screens#3]
Hi @Cj-Malone 

I found [this app](https://play.google.com/store/apps/details?id=co.Violet.screens) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under BSD 2-clause "Simplified" License and this guy is violating it;
* He is falsely claiming he made the app;
* Provide screenshots of your own app and a link to this repo.

**Comment by Cj-Malone** [comment]
Thanks, I've reached out to them (tuannamm100@gmail.com) and I'll see if I get a response.

But I think, if they add the licence details they are free to continue doing this? And there is the possibility that they, or both of us will be [removed from Google Play](https://www.xda-developers.com/google-threatening-removal-accessibility-services-play-store/) soon anyway.

**Comment by Poussinou** [comment]
Hum I'm not a big expert regarding the BSD 2-clause "Simplified" License. In my opinion, the best license is GNU GPL v3 for this kinf of work, but that's just my opinion...

Yes I'm aware of the article you provide in your response, that's really a shame...
This is where F-Droid will make sense!

**Comment by Poussinou** [comment]
The app has been removed. Please report here if you find other copies 👍
