### ISSUE TITLE
Multi not showing fixed screen

### ISSUE THREAD

**Issue by StarkAndy** [Cj-Malone/Screens#4]
I want windows to occupy the specific part of screen.Which will be not movable by user .Can you tell me please how can i do it ?

**Comment by Cj-Malone** [comment]
That's not possible unfortunately, this app dosen't use an offical API, it's basically a hack around [forcing split screen](https://github.com/Cj-Malone/Screens/blob/5c780537ca076e2ef0ca6ba9c12c59c679abc6a5/app/src/main/java/uk/co/keepawayfromfire/screens/ShortcutActivity.java#L90) and then [opening two intents at the same time](https://github.com/Cj-Malone/Screens/blob/5c780537ca076e2ef0ca6ba9c12c59c679abc6a5/app/src/main/java/uk/co/keepawayfromfire/screens/ShortcutActivity.java#L137).
